author:
    name: Amit Upadhyay
    twitter: amitu
    github: amitu
    email: blog@amitu.com

site:
    title: Amit Upadhyay
    production_url: http://amitu.com

TEMPLATE_CONTEXT_PROCESSORS:
    - django.core.context_processors.request
    - django.contrib.auth.context_processors.auth
    - _theme.views.context_processor

DISCUSS_SHORTNAME: amitu

