#!/bin/sh

set -x

wget -m http://localhost:9999/do/

set -e

rm -rf build
mv localhost:9999 build
cp CNAME build

ghp-import -b master -m "syncing" build

if [ "$1" == "push" ]
    git push --all
else
    echo "done. next: git push --all"
fi
